from extractors.libraries import *

def elastic_search_insert(es_index, index_name, celex_information):
    # """"""""""
    # Functionality: Insert the document in the ElasticSearch or OpenSearch Index
    #
    # Signature of the function:
    #  Input: 
    #       esIndex: ElasticSearch or OpenSearch connection
    #       indexName: Name of the index that needs to be created
    #       celexInformation: Information that needs to be inserted in the Index in JSON format
    # 
    #  Output:
    #       Insert the information in the ElasticSearch or OpenSearch Index keeping unqiue ID (_id) as the celex number
    # """"""""""
    doc = { 
            "bulgarian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['BG']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['BG']['summaryInformation']['summaryContent']
                    }
            },
            "spanish":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['ES']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['ES']['summaryInformation']['summaryContent']
                    }
            },
            "czech":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['CS']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['CS']['summaryInformation']['summaryContent']
                    }
            },
            "danish":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['DA']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['DA']['summaryInformation']['summaryContent']
                    }
            },
            "german":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['DE']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['DE']['summaryInformation']['summaryContent']
                    }
            },
            "estonian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['ET']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['ET']['summaryInformation']['summaryContent']
                    }
            },
            "greek":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['EL']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['EL']['summaryInformation']['summaryContent']
                    }
            },
            "english":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['EN']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['EN']['summaryInformation']['summaryContent']
                    }
            },
            "french":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['FR']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['FR']['summaryInformation']['summaryContent']
                    }
            },
            "irish":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['GA']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['GA']['summaryInformation']['summaryContent']
                    }
            },
            "croatian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['HR']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['HR']['summaryInformation']['summaryContent']
                    }
            },
            "italian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['IT']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['IT']['summaryInformation']['summaryContent']
                    }
            },
            "latvian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['LV']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['LV']['summaryInformation']['summaryContent']
                    }
            },
            "lithuanian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['LT']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['LT']['summaryInformation']['summaryContent']
                    }
            },
            "hungarian":
            { 
                "documentInformation":
                    {
                        "documentContent":celex_information['HU']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['HU']['summaryInformation']['summaryContent']
                    }
            },
            "maltese":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['MT']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['MT']['summaryInformation']['summaryContent']
                    }
            },
            "dutch":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['NL']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['NL']['summaryInformation']['summaryContent']
                    }
            },
            "polish":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['PL']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['PL']['summaryInformation']['summaryContent']
                    }
            },
            "portuguese":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['PT']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['PT']['summaryInformation']['summaryContent']
                    }
            },
            "romanian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['RO']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['RO']['summaryInformation']['summaryContent']
                    }
            },
            "slovak":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['SK']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['SK']['summaryInformation']['summaryContent']
                    }
            },
            "slovenian":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['SL']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['SL']['summaryInformation']['summaryContent']
                    }
            },
            "finnish":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['FI']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['FI']['summaryInformation']['summaryContent']
                    }
            },
            "swedish":
            {
                "documentInformation":
                    {
                        "documentContent":celex_information['SV']['documentInformation']['documentContent'],
                        "summaryContent":celex_information['SV']['summaryInformation']['summaryContent']
                    }
            }
        }
    _id = celex_information['_id']
    
    try:
        es_index.index(index=index_name,body=doc,id=_id)
    except Exception as e:
        logging.error('Indexing celex id \'{}\' failed to push in OpenSearch'.format(_id))